// components/ResultsDashboard.jsx
import { useState } from "react";
import { ScoreRing, AnalysisBar, Chip, SeverityBadge } from "./ui.jsx";

export default function ResultsDashboard({ result, preview, file, onReset }) {
  const [tab, setTab] = useState("overview");

  const verdictColor = result.verdict === "AUTHENTIC" ? "#06d6a0"
    : result.verdict === "SUSPICIOUS" ? "#ffd166" : "#ff4d6d";
  const verdictGlow = `${verdictColor}55`;

  const downloadReport = () => {
    const lines = [
      "══════════════════════════════════════════════════",
      "        DEEPTRACE AI — FORENSIC REPORT",
      "══════════════════════════════════════════════════",
      "",
      `FILE         : ${file?.name || "Unknown"}`,
      `DATE         : ${new Date().toUTCString()}`,
      `VERDICT      : ${result.verdict}`,
      `CONFIDENCE   : ${result.confidence}%`,
      `RISK LEVEL   : ${result.risk_level}`,
      `FAKE SCORE   : ${result.overall_score}/100`,
      `METHOD       : ${result.generation_method}`,
      "",
      "── FORENSIC SUMMARY ──────────────────────────────",
      result.forensic_summary,
      "",
      "── ANALYSIS SCORES ───────────────────────────────",
      ...Object.entries(result.analysis || {}).map(([k, v]) =>
        `${k.replace(/_/g," ").padEnd(22)}: ${v.score}/100`
      ),
      "",
      "── MANIPULATION REGIONS ──────────────────────────",
      ...result.manipulation_regions?.map(r => `[${r.severity}] ${r.region}: ${r.description}`) || [],
      "",
      "── TECHNICAL INDICATORS ──────────────────────────",
      ...result.technical_indicators?.map((t, i) => `${i + 1}. ${t}`) || [],
      "",
      "── RECOMMENDATIONS ───────────────────────────────",
      ...result.recommendations?.map((r, i) => `${i + 1}. ${r}`) || [],
      "",
      "── XAI EXPLAINABILITY ────────────────────────────",
      ...result.xai_highlights?.map((x, i) => `${i + 1}. ${x}`) || [],
      "",
      "══════════════════════════════════════════════════",
      "   Generated by DeepTrace AI Forensic Engine",
      "══════════════════════════════════════════════════",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `deeptrace-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  const TABS = [
    { id: "overview", label: "📊 Analysis" },
    { id: "xai", label: "🧠 XAI" },
    { id: "technical", label: "⚙ Technical" },
    { id: "report", label: "📋 Report" },
  ];

  return (
    <div style={{ animation: "fadeUp 0.5s ease" }}>

      {/* ── Verdict Banner ── */}
      <div style={{
        borderRadius: 20, padding: "28px 32px", marginBottom: 18,
        background: "rgba(8,11,18,0.85)",
        border: `1.5px solid ${verdictColor}33`,
        boxShadow: `0 0 50px ${verdictGlow}, inset 0 0 30px ${verdictColor}06`,
        backdropFilter: "blur(20px)"
      }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 20 }}>
          <div>
            <div style={{ fontSize: 10, fontFamily: "'Space Mono', monospace", color: "rgba(255,255,255,0.35)", letterSpacing: 2.5, textTransform: "uppercase", marginBottom: 8 }}>
              Forensic Verdict
            </div>
            <div style={{
              fontSize: "clamp(30px, 5vw, 46px)", fontWeight: 900, letterSpacing: -1,
              color: verdictColor, fontFamily: "'Space Mono', monospace",
              textShadow: `0 0 40px ${verdictGlow}`
            }}>
              {result.verdict}
            </div>
            <div style={{ marginTop: 10, display: "flex", flexWrap: "wrap", gap: 12 }}>
              <span style={{ fontSize: 12, color: "rgba(255,255,255,0.45)" }}>
                Method: <span style={{ color: "rgba(255,255,255,0.8)" }}>{result.generation_method}</span>
              </span>
              <span style={{ color: "rgba(255,255,255,0.15)" }}>|</span>
              <span style={{ fontSize: 12, color: "rgba(255,255,255,0.45)" }}>
                Risk: <SeverityBadge level={result.risk_level} />
              </span>
            </div>
          </div>
          <div style={{ display: "flex", gap: 28, flexWrap: "wrap" }}>
            <ScoreRing score={result.confidence} label="Confidence" color={verdictColor} size={88} />
            <ScoreRing
              score={result.overall_score} label="Fake Score"
              color={result.overall_score > 70 ? "#ff4d6d" : result.overall_score > 40 ? "#ffd166" : "#06d6a0"}
              size={88}
            />
          </div>
        </div>
        <div style={{ marginTop: 20, padding: "14px 18px", background: "rgba(255,255,255,0.04)", borderRadius: 10, borderLeft: `3px solid ${verdictColor}88` }}>
          <p style={{ margin: 0, fontSize: 13, color: "rgba(255,255,255,0.68)", lineHeight: 1.85 }}>
            {result.forensic_summary}
          </p>
        </div>
      </div>

      {/* ── Preview + Regions ── */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 18 }}>
        {preview && (
          <div style={{ borderRadius: 14, overflow: "hidden", border: "1px solid rgba(255,255,255,0.07)", position: "relative", minHeight: 200 }}>
            <img src={preview} alt="Analyzed" style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
            <div style={{ position: "absolute", top: 10, right: 10, padding: "4px 10px", background: "rgba(0,0,0,0.75)", borderRadius: 6, fontSize: 10, fontFamily: "'Space Mono', monospace", color: "#00f5a0", letterSpacing: 1 }}>
              ANALYZED
            </div>
            <div style={{ position: "absolute", bottom: 10, left: 10, right: 10, display: "flex", flexWrap: "wrap", gap: 5 }}>
              {result.manipulation_regions?.slice(0, 4).map((r, i) => (
                <span key={i} style={{
                  padding: "3px 8px", borderRadius: 5, fontSize: 10, fontWeight: 700,
                  fontFamily: "'Space Mono', monospace", color: "#080b12",
                  background: r.severity === "HIGH" ? "#ff4d6d" : r.severity === "MEDIUM" ? "#ffd166" : "#06d6a0"
                }}>
                  {r.region}
                </span>
              ))}
            </div>
          </div>
        )}

        <div style={{ background: "rgba(255,255,255,0.025)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 14, padding: 20 }}>
          <h3 style={{ fontSize: 11, fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: 2, color: "rgba(255,255,255,0.35)", margin: "0 0 16px" }}>
            Manipulation Regions
          </h3>
          {result.manipulation_regions?.map((r, i, arr) => (
            <div key={i} style={{
              display: "flex", alignItems: "flex-start", gap: 12, padding: "10px 0",
              borderBottom: i < arr.length - 1 ? "1px solid rgba(255,255,255,0.05)" : "none"
            }}>
              <div style={{
                width: 8, height: 8, borderRadius: "50%", marginTop: 5, flexShrink: 0,
                background: r.severity === "HIGH" ? "#ff4d6d" : r.severity === "MEDIUM" ? "#ffd166" : "#06d6a0",
                boxShadow: `0 0 8px ${r.severity === "HIGH" ? "#ff4d6d" : r.severity === "MEDIUM" ? "#ffd166" : "#06d6a0"}`
              }} />
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 2, color: "#fff" }}>{r.region}</div>
                <div style={{ fontSize: 11, color: "rgba(255,255,255,0.42)", lineHeight: 1.5 }}>{r.description}</div>
              </div>
              <SeverityBadge level={r.severity} />
            </div>
          ))}
        </div>
      </div>

      {/* ── Tabs ── */}
      <div style={{ background: "rgba(255,255,255,0.025)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 16, overflow: "hidden" }}>
        <div style={{ display: "flex", borderBottom: "1px solid rgba(255,255,255,0.07)", overflowX: "auto" }}>
          {TABS.map(t => (
            <button key={t.id} onClick={() => setTab(t.id)} style={{
              padding: "14px 20px", border: "none",
              background: tab === t.id ? "rgba(0,245,160,0.07)" : "transparent",
              color: tab === t.id ? "#00f5a0" : "rgba(255,255,255,0.38)",
              borderBottom: tab === t.id ? "2px solid #00f5a0" : "2px solid transparent",
              cursor: "pointer", fontSize: 13,
              fontFamily: "'IBM Plex Sans', sans-serif",
              transition: "all 0.2s", whiteSpace: "nowrap"
            }}>
              {t.label}
            </button>
          ))}
        </div>

        <div style={{ padding: 24 }}>

          {/* Overview */}
          {tab === "overview" && (
            <div>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, marginBottom: 24 }}>
                {Object.entries(result.analysis || {}).slice(0, 3).map(([key, val]) => (
                  <div key={key} style={{ padding: 14, background: "rgba(255,255,255,0.025)", borderRadius: 10, border: "1px solid rgba(255,255,255,0.06)", textAlign: "center" }}>
                    <ScoreRing
                      score={val.score} label={key.replace(/_/g, " ")}
                      color={val.score > 70 ? "#ff4d6d" : val.score > 40 ? "#ffd166" : "#06d6a0"}
                      size={76}
                    />
                  </div>
                ))}
              </div>
              {Object.entries(result.analysis || {}).map(([key, val], i) => (
                <AnalysisBar key={key} label={key.replace(/_/g, " ")} score={val.score} findings={val.findings} details={val.details} delay={i * 80} />
              ))}
            </div>
          )}

          {/* XAI */}
          {tab === "xai" && (
            <div>
              <div style={{ marginBottom: 20, padding: 16, background: "rgba(0,245,160,0.04)", borderRadius: 12, border: "1px solid rgba(0,245,160,0.12)" }}>
                <div style={{ fontSize: 11, color: "#00f5a0", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 8 }}>
                  Explainable AI (XAI) — Why this decision?
                </div>
                <p style={{ margin: 0, fontSize: 12, color: "rgba(255,255,255,0.48)", lineHeight: 1.75 }}>
                  Unlike black-box models, DeepTrace provides transparent GRAD-CAM attribution maps and SHAP-based feature importance to explain every detection decision — making it legally defensible.
                </p>
              </div>
              {result.xai_highlights?.map((h, i) => (
                <div key={i} style={{ display: "flex", gap: 14, padding: "14px 0", borderBottom: i < result.xai_highlights.length - 1 ? "1px solid rgba(255,255,255,0.05)" : "none" }}>
                  <div style={{
                    width: 32, height: 32, borderRadius: 8, flexShrink: 0,
                    background: "linear-gradient(135deg, #00f5a0, #00d9f5)",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    color: "#080b12", fontWeight: 900, fontSize: 14, fontFamily: "'Space Mono', monospace"
                  }}>{i + 1}</div>
                  <p style={{ margin: 0, paddingTop: 6, fontSize: 13, color: "rgba(255,255,255,0.68)", lineHeight: 1.75 }}>{h}</p>
                </div>
              ))}
              <div style={{ marginTop: 22, padding: "14px 18px", background: "rgba(0,217,245,0.04)", borderRadius: 10, border: "1px solid rgba(0,217,245,0.12)" }}>
                <div style={{ fontSize: 11, color: "#00d9f5", fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: 1, marginBottom: 8 }}>
                  Demographic Fairness Assessment
                </div>
                <p style={{ margin: 0, fontSize: 12, color: "rgba(255,255,255,0.48)", lineHeight: 1.75 }}>
                  This model was trained on FaceForensics++, Celeb-DF, DFDC, and WildDeepfake — covering diverse ethnicities, ages, genders, and lighting conditions — to ensure equitable detection accuracy across demographic groups.
                </p>
              </div>
            </div>
          )}

          {/* Technical */}
          {tab === "technical" && (
            <div>
              <h4 style={{ fontSize: 11, fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: 2, color: "rgba(255,255,255,0.35)", margin: "0 0 16px" }}>
                Technical Indicators Detected
              </h4>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 28 }}>
                {result.technical_indicators?.map((ind, i) => (
                  <div key={i} style={{ padding: "12px 14px", background: "rgba(255,255,255,0.025)", borderRadius: 10, border: "1px solid rgba(255,255,255,0.06)", display: "flex", gap: 10, alignItems: "flex-start" }}>
                    <span style={{ color: "#ffd166", fontSize: 11, marginTop: 2, flexShrink: 0 }}>▸</span>
                    <span style={{ fontSize: 12, color: "rgba(255,255,255,0.6)", lineHeight: 1.6 }}>{ind}</span>
                  </div>
                ))}
              </div>
              <h4 style={{ fontSize: 11, fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: 2, color: "rgba(255,255,255,0.35)", margin: "0 0 14px" }}>
                Detection Architecture
              </h4>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                {["EfficientNet-B4", "Vision Transformer (ViT)", "DCT Frequency CNN", "GRAD-CAM XAI", "Multimodal Fusion", "Adversarial Hardening", "SHAP Explainer", "FaceNet Landmarks"].map(m => (
                  <Chip key={m}>{m}</Chip>
                ))}
              </div>
            </div>
          )}

          {/* Report */}
          {tab === "report" && (
            <div>
              <div style={{ padding: "20px 22px", background: "rgba(255,255,255,0.025)", borderRadius: 12, border: "1px solid rgba(255,255,255,0.07)", fontFamily: "'Space Mono', monospace", marginBottom: 22 }}>
                <div style={{ fontSize: 9, color: "rgba(255,255,255,0.2)", letterSpacing: 2, marginBottom: 14 }}>
                  ── DEEPTRACE AI FORENSIC REPORT ─────────────────────────
                </div>
                {[
                  ["FILE", file?.name],
                  ["DATE", new Date().toUTCString()],
                  ["VERDICT", result.verdict],
                  ["CONFIDENCE", `${result.confidence}%`],
                  ["RISK LEVEL", result.risk_level],
                  ["FAKE SCORE", `${result.overall_score}/100`],
                  ["METHOD", result.generation_method],
                ].map(([k, v]) => (
                  <div key={k} style={{ fontSize: 11, color: "rgba(255,255,255,0.5)", lineHeight: 2.1 }}>
                    {k.padEnd(14)}: <span style={{ color: k === "VERDICT" ? verdictColor : "#fff" }}>{v}</span>
                  </div>
                ))}
                <div style={{ fontSize: 9, color: "rgba(255,255,255,0.2)", letterSpacing: 2, margin: "14px 0 10px" }}>
                  ── SUMMARY ──────────────────────────────────────────────
                </div>
                <p style={{ fontSize: 11, color: "rgba(255,255,255,0.6)", lineHeight: 1.8, margin: 0 }}>
                  {result.forensic_summary}
                </p>
              </div>

              <h4 style={{ fontSize: 11, fontFamily: "'Space Mono', monospace", textTransform: "uppercase", letterSpacing: 2, color: "rgba(255,255,255,0.35)", margin: "0 0 14px" }}>
                Recommendations
              </h4>
              {result.recommendations?.map((rec, i, arr) => (
                <div key={i} style={{ display: "flex", gap: 12, padding: "12px 0", borderBottom: i < arr.length - 1 ? "1px solid rgba(255,255,255,0.05)" : "none" }}>
                  <div style={{
                    width: 24, height: 24, borderRadius: "50%", flexShrink: 0,
                    border: "1.5px solid #00f5a0",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    fontSize: 10, color: "#00f5a0", fontFamily: "'Space Mono', monospace"
                  }}>{i + 1}</div>
                  <p style={{ margin: 0, fontSize: 13, color: "rgba(255,255,255,0.65)", paddingTop: 2, lineHeight: 1.65 }}>{rec}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* ── Action Buttons ── */}
      <div style={{ display: "flex", gap: 12, marginTop: 18, justifyContent: "flex-end", flexWrap: "wrap" }}>
        <button onClick={onReset} style={{
          padding: "12px 26px", borderRadius: 50,
          border: "1.5px solid rgba(255,255,255,0.13)",
          background: "transparent", color: "rgba(255,255,255,0.55)",
          cursor: "pointer", fontFamily: "'IBM Plex Sans', sans-serif",
          fontSize: 14, transition: "all 0.2s"
        }}>
          ← Analyze Another
        </button>
        <button onClick={downloadReport} style={{
          padding: "12px 26px", borderRadius: 50,
          background: "linear-gradient(135deg, #00f5a0, #00d9f5)",
          border: "none", color: "#080b12", fontWeight: 700,
          cursor: "pointer", fontFamily: "'IBM Plex Sans', sans-serif",
          fontSize: 14, boxShadow: "0 8px 28px #00f5a044"
        }}>
          ↓ Download Report
        </button>
      </div>
    </div>
  );
}
